core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from myshop.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("myshop.urls")),
    # path("user/", include("userauths.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myshop/urls.py
from django.urls import path
from myshop.views import add_to_cart, ajax_add_review, cart_view, index, product_detail_view, product_list_view, category_list_view, category_product_list_view, search_view, tag_list, vendor_detail_view, vendor_list_view

app_name = "myshop"

urlpatterns = [
    # Home page
    path('', index, name='index'),
    path("products/", product_list_view, name="product-list"),
    path("product/<pid>/", product_detail_view, name="product-detail"),

    # Category
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list_view, name="category-product-list"),

    # Vendor
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),

    # Tags
    path("product/tag/<slug:tag_slug>/", tag_list, name="tags"),

    # Add Review
    path("ajax_add_review/<int:pid>/", ajax_add_review , name="ajax_add_review"),

    # Search
    path("search/", search_view, name="search"),

    # add to cart
    path("add-to-cart/", add_to_cart, name="add-to-cart" ),


    #Cart page 
    path("cart/", cart_view, name="cart")
]

myshop/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
# from userauths.models import User
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

STATUS_CHOICE = (
    ("process", "Processing"),
    ("Shipped", "Shipped"),
    ("delivered", "Delivered"),
)

STATUS = (
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In Review"),
    ("published", "Published"),
)


RATING = (
    ( 1, "★☆☆☆☆"),
    ( 2, "★★☆☆☆"),
    ( 3, "★★★☆☆"),
    ( 4, "★★★★☆"),
    ( 5, "★★★★★"),
)



def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Category(models.Model):
    cid = ShortUUIDField(unique=True, length= 10, max_length=30, prefix="cat", alphabet="abcdefgh12345") # типо cat4215gcda
    title = models.CharField(max_length=100, default="Food")
    image = models.ImageField(upload_to="category", default="category.jpg")

    class Meta:
        verbose_name_plural = "Categories" #в админке будет Categories вместо Categorys

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title
    

class Tags(models.Model):
    pass



class Vendor(models.Model):
    vid = ShortUUIDField(unique=True, length= 10, max_length=30, prefix="ven", alphabet="abcdefgh12345") # типо ven4215gcda

    title = models.CharField(max_length=100, default="Itstep")
    image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    cover_image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    description = models.TextField(null=True, blank=True, default="I am amazing vendor")

    address = models.CharField(max_length=100, default="123 Main Street.")
    contact = models.CharField(max_length=100, default="+998 (99) 060")
    chat_resp_time = models.CharField(max_length=100, default="100")
    shipping_on_time = models.CharField(max_length=100, default="100")
    authentic_rating = models.CharField(max_length=100, default="100")
    days_return = models.CharField(max_length=100, default="100")
    warranty_period = models.CharField(max_length=100, default="100")



    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Vendors" #в админке будет Vendors

    def vendor_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title
    
class Product(models.Model):
    pid = ShortUUIDField(unique=True, length= 10, max_length=30, alphabet="abcdefgh12345") # типо fde4215gcda

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True, related_name="product")

    title = models.CharField(max_length=100, default="Banana")
    image = models.ImageField(upload_to=user_directory_path, default="product.jpg")
    description = models.TextField(null=True, blank=True, default="This is the product")

    price = models.DecimalField(max_digits=7777777777, decimal_places=2, default = "1.99") # 2 цифры после точки -> 34.99
    old_price = models.DecimalField(max_digits=7777777777, decimal_places=2, default = "1.99") # 2 цифры после точки -> 34.99
    
    specification = models.TextField(null=True, blank=True)
    type = models.CharField(max_length=100, default="Organic", null=True, blank=True)
    stock_count = models.CharField(max_length=100, default="10", null=True, blank=True)
    life = models.CharField(max_length=100, default="100 days",null=True, blank=True)
    mfd = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    
    tags = TaggableManager(blank=True)
    # tags = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True)

    product_status = models.CharField(choices= STATUS, max_length=10, default="in_review")

    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    digital = models.BooleanField(default=False)

    sku = ShortUUIDField(unique=True, length= 5, max_length=10, prefix="sku", alphabet="1234567890") # типо 4838763192

    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True, blank=True)


    class Meta:
        verbose_name_plural = "Products" #в админке будет Products

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title
    
    def get_percentage(self):
        new_price = ((self.old_price - self.price) / self.old_price) * 100 #математика чтобы узнать на сколько процентов скидка
        return new_price
    
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images", default="product.jpg")
    product= models.ForeignKey(Product, related_name= "p_images", on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)



    class Meta:
        verbose_name_plural = "Product Images" #в админке будет Product Images





###################################### Cart, Order, OrderItems и Address ######################################



class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7777777777, decimal_places=2, default = "1.99") # 2 цифры после точки -> 34.99
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices=STATUS_CHOICE, max_length=30, default="processing")
    

    class Meta:
        verbose_name_plural = "Cart Order" #в админке будет Cart Order

    


class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length= 200)
    product_status = models.CharField(max_length= 200)
    item = models.CharField(max_length= 200)
    image = models.CharField(max_length=200)
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=7777777777, decimal_places=2, default = "1.99") # 2 цифры после точки -> 34.99
    total = models.DecimalField(max_digits=7777777777, decimal_places=2, default = "1.99") # 2 цифры после точки -> 34.99

    class Meta:
        verbose_name_plural = "Cart Order Items" #в админке будет Cart Order Items

    def order_img(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))
    
    
    



###################################### Product Review, wishlist, Address ######################################


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True,related_name="reviews")
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    
    class Meta:
        verbose_name_plural = "Product Reviews" #в админке будет Product Reviews


    def __str__(self):
        return self.product.title
    
    def get_rating(self):
        return self.rating
    



class wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    
    class Meta:
        verbose_name_plural = "wishlists" #в админке будет wishlists


    def __str__(self):
        return self.product.title


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Address" #в админке будет Address

myshop/forms.py
from django import forms
from myshop.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'write review'}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

myshop/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from myshop.models import Product, Category, Vendor, CartOrder, CartOrderItems, wishlist, ProductImages, ProductReview, Address
from taggit.models import Tag
from django.db.models import Avg
from myshop.forms import ProductReviewForm
from django.template.loader import render_to_string

def index(request):
    # products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published", featured= True)

    context = {
        "products": products
    }
    return render(request, 'myshop/index.html', context )


def product_list_view(request):
    products = Product.objects.filter(product_status="published", )

    context = {
        "products": products
    }
    return render(request, 'myshop/product-list.html', context )


def category_list_view(request):
    
    categories = Category.objects.all()
    context = {
        "categories": categories
    }
    return render(request, 'myshop/category-list.html', context )



def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status="published", category= category)

    context = {
        "category": category,
        "products": products,
    }

    return render(request, "myshop/category-product-list.html", context)



def vendor_list_view(request):
    vendors = Vendor.objects.all()

    context = {
        "vendors": vendors
    }
    return render(request, "myshop/vendor-list.html", context)


def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid = vid)
    products = Product.objects.filter(vendor=vendor, product_status="published")

    context = {
        "vendor": vendor,
        "products": products
    }
    return render(request, "myshop/vendor-detail.html", context)


def product_detail_view(request, pid):
    product = Product.objects.get(pid = pid)
    # product = get_object_or_404(Product, pid = pid)
    products = Product.objects.filter(category = product.category).exclude(pid=pid)

    # взять все отзывы смотря ток на продукты 
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    # средняя оценка 
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))


    review_form = ProductReviewForm()

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    p_image = product.p_images.all()

    context = {
        "p": product,
        "make_review": make_review,
        "review_form": review_form,
        "p_image": p_image,
        "average_rating": average_rating,
        "reviews": reviews,
        "products": products,
    }

    return render(request, "myshop/product-detail.html", context)

def tag_list(request, tag_slug=None):
    products =Product.objects.filter(product_status="published").order_by("-id")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        products = products.filter(tags__in=[tag])          #искать по тагу который совпадает из моделей

    context = {
        "products": products,
        "tag": tag
    }

    return render(request, "myshop/tag.html", context)


def ajax_add_review(request, pid):
    product = Product.objects.get(pk = pid)
    user = request.user

    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )

    context = {
        "user": user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
        {
        'bool': True,
        'context': context,
        'average_reviews': average_reviews
        }
    )


def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains = query, description__icontains = query).order_by("-date")

    context = {
        "products": products,
        "query": query,
    }

    return render(request, "myshop/search.html", context)


def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid'],

    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product

    return JsonResponse({"data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})


def cart_view(request):
    cart_total_amout = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amout += int(item['qty']) * float(item['price'])
        
        return render(request, "myshop/cart.html", {"cart_data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amout': cart_total_amout} )

    else:
        messages.warning(request, "Your cart is empty")
        return redirect("myshop:index")

myshop/templates/myshop/category-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

        <main class="main">
            <div class="page-header mt-30 mb-75">
                <div class="container">
                    <div class="archive-header">
                        <div class="row align-items-center">
                            <div class="col-xl-3">
                                <h1 class="mb-15">Categories</h1>
                                <div class="breadcrumb">
                                    <a href="index.html" rel="nofollow">Home<i class="fi-rs-home mr-5"></i></a>
                                    <span></span> Category
                                </div>
                            </div>
                            <!-- <div class="col-xl-9 text-end d-none d-xl-block">
                                <ul class="tags-list">
                                    <li class="hover-up">
                                        <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Shopping</a>
                                    </li>
                                    <li class="hover-up active">
                                        <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Recips</a>
                                    </li>
                                    <li class="hover-up">
                                        <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Kitchen</a>
                                    </li>
                                    <li class="hover-up">
                                        <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>News</a>
                                    </li>
                                    <li class="hover-up mr-0">
                                        <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Food</a>
                                    </li>
                                </ul>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="page-content mb-50">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-9">
                            <div class="shop-product-fillter mb-50 pr-30">
                                <div class="totall-product">
                                    <h2>
                                        <img class="w-36px mr-10" src="assets/imgs/theme/icons/category-1.svg" alt="" />
                                        {{ categories.count }} Categories
                                    </h2>
                                </div>
                            
                            </div>
                            <div class="loop-grid pr-30">
                                <div class="row">

                                    {% for c in categories %}
                                    <article class="col-xl-4 col-lg-6 col-md-6 text-center hover-up mb-30 animated">
                                        <div class="post-thumb">
                                            <a href="{% url 'myshop:category-product-list' c.cid %}">
                                                <img class="border-radius-15" src="{{ c.image.url }}" alt="" />
                                            </a>
                                            <div class="entry-meta">
                                                <a class="entry-meta meta-2" href="blog-category-grid.html"><i class="fi-rs-heart"></i></a>
                                            </div>
                                        </div>
                                        <div class="entry-content-2">
                                            <!-- <h6 class="mb-10 font-sm"><a class="entry-meta text-muted" href="blog-category-grid.html">Side Dish</a></h6> -->
                                            <h4 class="post-title mb-15">
                                                <a href="{% url 'myshop:category-product-list' c.cid %}">{{ c.title }}</a>
                                            </h4>
                                            <div class="entry-meta font-xs color-grey mt-10 pb-10">
                                                <div>
                                                    <span class="hit-count mr-10">{{ c.category.count }} Product{{ c.category.count|pluralize}}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </article>
                                    {% endfor %}
                                    
                                </div>
                            </div>
                            <!-- <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination justify-content-start">
                                        <li class="page-item">
                                            <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                                        </li>
                                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                        <li class="page-item"><a class="page-link" href="#">6</a></li>
                                        <li class="page-item">
                                            <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                                        </li>
                                    </ul>
                                </nav>
                            </div> -->
                        </div>
                        <div class="col-lg-3 primary-sidebar sticky-sidebar">
                            <div class="widget-area">
                                
                                <div class="sidebar-widget widget-category-2 mb-50">
                                    <h5 class="section-title style-1 mb-30">Category</h5>
                                    <ul>
                                        {% for c in categories %}
                                        <li>
                                            <a href="shop-grid-right.html"> <img src="{{c.image.url}}" alt="" />{{c.title}}</a><span class="count">{{c.category.count}}</span>
                                        </li>
                                        {% endfor %}
                                       
                                    </ul>
                                </div>
                                                                                                        
                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock content %}

myshop/templates/myshop/category-product-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

        <main class="main">
            <div class="page-header mt-30 mb-50">
                <div class="container">
                    <div class="archive-header">
                        <div class="row align-items-center">
                            <div class="col-xl-3">
                                <h1 class="mb-15">{{category.title}}</h1>
                                <div class="breadcrumb">
                                    <a href="{{index.html}}" rel="nofollow">Home<i class="fi-rs-home mr-5"></i></a>
                                    <span></span> Shop <span></span> {{category.title}}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="container mb-30">
                <div class="row">
                    <div class="col-12">
                        <div class="shop-product-fillter">
                            <div class="totall-product">
                                <p>We found <strong class="text-brand">{{products.count}}</strong> item{{products.count|pluralize}} for you</p>
                            </div>
                            
                        </div>
                        <div class="row product-grid">

                            {% for p in products %}
                            <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                                <div class="product-cart-wrap mb-30 wow animate__animated animate__fadeIn" data-wow-delay=".1s">
                                    <div class="product-img-action-wrap">
                                        <div class="product-img product-img-zoom">
                                            <a href="{% url 'myshop:product-detail' p.pid %}">
                                                <img class="default-img" src="{{ p.image.url }}" alt="" />
                                                <img class="hover-img" src="{{ p.image.url }}" alt="" />
                                            </a>
                                        </div>
                                        <div class="product-action-1">
                                            <a aria-label="Add To Wishlist" class="action-btn" href="shop-wishlist.html"><i class="fi-rs-heart"></i></a>
                                            <a aria-label="Compare" class="action-btn" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a>
                                            <a aria-label="Quick view" class="action-btn" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i class="fi-rs-eye"></i></a>
                                        </div>
                                        <div class="product-badges product-badges-position product-badges-mrg">
                                            <span class="hot">-{{p.get_percentage|floatformat:0}}%</span>
                                        </div>
                                    </div>
                                    <div class="product-content-wrap">
                                        <div class="product-category">
                                            <a href="shop-grid-right.html">{{ p.category.title }}</a>
                                        </div>
                                        <h2><a href="{% url 'myshop:product-detail' p.pid %}">{{ p.title }}</a></h2>
                                        <div class="product-rate-cover">
                                            <div class="product-rate d-inline-block">
                                                <div class="product-rating" style="width: 90%"></div>
                                            </div>
                                            <span class="font-small ml-5 text-muted"> (4.0)</span>
                                        </div>
                                        <div>
                                            <span class="font-small text-muted">By <a href="vendor-details-1.html">{{ p.vendor.title }}</a></span>
                                        </div>
                                        <div class="product-card-bottom">
                                            <div class="product-price">
                                                <span>{{ p.price }}</span>
                                                <span class="old-price">{{ p.old_price }}</span>
                                            </div>
                                            <div class="add-cart">
                                                <a class="add" href="shop-cart.html"><i class="fi-rs-shopping-cart mr-5"></i>Add </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                        </div>
                        <!--product grid-->
                        
                        
                    </div>
                </div>
            </div>
        </main>
      
       
{% endblock content %}